ShcoolWork/urls.py
# coding=utf-8

"""ShcoolWork URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    # url(r'^home/', include('home.urls', namespace='home')),
    # url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^role/', include('role.urls', namespace='role'))
]

home/urls.py
# coding=utf-8

from django.conf.urls import url
from django.contrib import admin

import views

urlpatterns = [
     url(r'^$', views.LoginView.as_view(), name='login'),
     url(r'^sign_in/$', views.sign_in, name='sign_in'),
     url(r'^sign_out/$', views.sign_out, name='sign_out'),
]

home/models.py
# coding=utf-8

from __future__ import unicode_literals


# Create your models here.

home/views.py
# coding=utf-8

from django.shortcuts import render
from django.shortcuts import HttpResponse, HttpResponseRedirect
from django.views import generic
import datetime
from django.contrib.auth import models, authenticate, login, logout
# Create your views here.


class LoginView(generic.View):

    templates_file = 'home/index.html'

    def get(self, request):

        if request.user.is_authenticated():
            return HttpResponseRedirect('/role/home')

        if 'error' in request.GET and request.GET['error']:
            error_code = request.GET['error']
            if error_code == '1':
                error_txt = "用户名或密码不能为空"
            elif error_code == '2':
                error_txt = "用户名与密码不匹配或该用户不存在"
            else:
                error_txt = "未知错误,请与管理员联系!"
        else:
            error_txt = ""

        context = {
            "error_txt": error_txt,
            "e": "waaaaa",
        }

        return render(request,
                      self.templates_file,
                      context)


def sign_in(request):

    if request.method == "POST":

        postdata = request.POST

        if 'username' in postdata and postdata['username'] and 'password' in postdata and postdata['password']:
            username = postdata['username']
            password = postdata['password']
        else:
            return HttpResponseRedirect("/?error=1")

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect('/?error=2')

        # return render(request,
        #               'role/upload.html',
        #               )

    else:
        return render(
            request,
            '/role/home',
        )


def sign_out(request):

    logout(request)

    return HttpResponseRedirect('/')


def index(request):
    templates = 'home/index.html'
    # templates = 'role/regist.html'

    # l = ['a', 'b', 'c', 'd', 'e', ]
    #
    # d = {
    #     'A': 'hello',
    #     'B': 'world',
    # }
    context = {
        # 'msg': 'hello',
        # 'time': datetime.datetime.now(),
        # 'list': l,
        # 'dict': d,
    }

    return render(
        request,
        templates,
        context
    )


def TeacherRegist(request):

    template = 'role/regist.html'
    print request
    # template = 'home/index.html'
    context = {

    }

    return render(
        request,
        template,
        context,
    )


def StudentRegist(request):

    template = 'role/regist.html'

    return render(
        request,
        template,
    )

templates/home/index.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>home</title>
    <link rel="stylesheet" href="{% static 'css/log_in.css' %}">
</head>
<body>

<form action="{% url 'home:sign_in' %}" method="post" class="form-horizontal">

    {% csrf_token %}
{#    <input type="submit" value="regist">#}
    <div class="login">

        <div id="line">
            <h3>课件管理系统</h3>
        </div>

        <div class="login-txt">
            <h3 id="qwe">用户登录</h3>

            <div class="form-group">
                <label for="username">用户名</label>
                <input type="text" name="username" class="form-control" placeholder="Username">

            </div>

            <div class="form-group">
                 <label for="password">密　码</label>
                 <input type="password" name="password" class="form-control" placeholder="Password">
            </div>

                {% if error_txt %}
            <div class="error">
                    {{ error_txt }}
            </div>
                {% endif %}

             <div class="sign_in">
                <input type="submit" class="btn btn-default btn-sm" id="sign" value="LOG IN">
             </div>
        </div>
    </div>

</form>

{#{{ msg }}#}
{#Time is: {{ time }}#}
{##}
{#{% for l in list %}#}
{#    <hr>#}
{#    {{ l }}#}
{#{% endfor %}#}
{##}
{#{{ dict }}#}

{#{% for key, v in dict %}#}
{#    <br>#}
{#    {{ key }} | {{ v }}#}
{#{% endfor %}#}


</body>
</html>