ShcoolWork/urls.py
# coding=utf-8

"""ShcoolWork URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    # url(r'^home/', include('home.urls', namespace='home')),
    # url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^role/', include('role.urls', namespace='role'))
]

home/urls.py
# coding=utf-8

from django.conf.urls import url
from django.contrib import admin

import views

urlpatterns = [
     url(r'^$', views.LoginView.as_view(), name='login'),
     url(r'^sign_in/$', views.sign_in, name='sign_in'),
     url(r'^sign_out/$', views.sign_out, name='sign_out'),
]

role/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from role import views


urlpatterns = [
    url(r'^home/$', views.index, name='index'),
    url(r'^regist/$', views.Regist.as_view(), name='regist'),
    url(r'^register/$', views.register, name='register'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^download/$', views.download, name='download'),
    url(r'^delete/$', views.Delete, name='delete'),
]

role/models.py
# coding=utf-8

from __future__ import unicode_literals
from django.db import models

from django.utils import timezone
from django.contrib.auth.models import *

import time, random, re
from home.models import *

# Create your models here.


def show_name(user):
    name = user.first_name + user.last_name
    if name:
        return name
    else:
        return user.username


class Teacher(models.Model):
    number = models.IntegerField(unique=True, null=True, blank=True)
    user = models.OneToOneField(User)

    def __unicode__(self):
        return show_name(self.user)


class Student(models.Model):
    number = models.IntegerField(unique=True, null=True, blank=True)
    user = models.OneToOneField(User)

    def __unicode__(self):
        return show_name(self.user)


#  科目
class Subject(models.Model):
    number = models.IntegerField(unique=True)
    name = models.CharField(max_length=32, unique=True)
    teacher = models.ForeignKey(Teacher, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = '科目'
        verbose_name_plural = '科目'


# 班级
class StuToSub(models.Model):
    student = models.ForeignKey(Student)
    subject = models.ForeignKey(Subject)

    class Meta:
        verbose_name = '学生科目关系'
        verbose_name_plural = '学生科目关系'


# 重命名文件名
def resource_file_path(instance, filename):
    # file_time = time.strftime('%Y%m%d%H%M%s', time.localtime(time.time()))
    ft = time.strftime('%Y%m%d%H%M%S', time.localtime(time.time()))
    # format = re.search("\.\w+$",  filename)
    format = re.findall("\.\w+$", filename)
    filename = str(ft) + instance.name + format[0]
    return '/'.join(['courseware', 'resource', time.strftime('%m%d', time.localtime(time.time())), filename])


# 课件
class Courseware(models.Model):
    # number = models.IntegerField(unique=True, null=True, )
    name = models.CharField(max_length=128)
    pub_datetime = models.DateTimeField(auto_now_add=True)
    subject = models.ManyToManyField(Subject)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    file = models.FileField(upload_to=resource_file_path)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'role_courseware'
        app_label = 'role'
        verbose_name = '课件'
        verbose_name_plural = '课件'

role/views.py
# coding=utf-8
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, render_to_response
from django.contrib.auth import models
from django.views import generic
from django import forms
from wsgiref.util import FileWrapper  # 引用下载


from role.models import *

import os
import models
import re
import time
import mimetypes # 下载

def index(request):
    # templates = 'role/regist.html'
    if request.user.is_superuser:
        user_type = 'super'
        return HttpResponseRedirect('/admin')

    else:
        user_type = Group.objects.get(user=request.user.id)
        print user_type
    name = request.user.get_full_name()
    sub_list = {}

    if 'Student' == user_type.name:
        student = Student.objects.get(user=request.user.id)
        subject_list = StuToSub.objects.filter(student=student.id)
        print subject_list.values()
        for l in subject_list.values():
            id = l['subject_id']
            s = Subject.objects.get(id=id)
            print s
            sub_list[str(id)] = s.name
        print sub_list
        name = student.__unicode__()
    elif 'Teacher' == user_type.name:
        teacher = Teacher.objects.get(user=request.user.id)
        subject_list = Subject.objects.filter(teacher=teacher)
        name = teacher.__unicode__()
        for p in subject_list:
            sub_list[p.id] = p.name

    print sub_list

    clicked = -1
    click_name = ''
    courseware_list = {}
    if 'clicked' in request.GET and request.GET['clicked']:
        click_id = request.GET['clicked']
        subject = Subject.objects.get(id=click_id)
        click_name = subject.name
        courseware = Courseware.objects.filter(subject=click_id)
        for i in courseware:
            print i
            courseware_list[str(i.id)] = i.name
        clicked = click_id
        print courseware_list

    return_info = ''
    if 'returninfo' in request.GET and request.GET['returninfo']:
        return_info = request.GET['returninfo']

    context = {
        'page_type': 'home',
        'msg ': 'sdawdaw',
        'subject_list': sub_list,
        'courseware_list': courseware_list,
        'user_type': user_type,
        'user_name': name,
        'click_id': clicked,
        'click_name': click_name,
        'returninfo': return_info,
    }

    return render(
        request,
        "role/main_menu.html",
        context,
    )


# 上传
def upload(request):

    print request.GET
    if request.method == 'POST':

        if 'subject' in request.POST and request.POST['subject']:
            click_id = request.POST['subject']
            subject = Subject.objects.get(id=click_id)

        if 'upfile' in request.FILES and request.FILES['upfile']:
            file = request.FILES['upfile']
        else:
            return HttpResponseRedirect('/role/home?returninfo=file&clicked=' + str(click_id))
        if 'name' in request.POST and request.POST['name']:
            name = request.POST['name']
        else:
            return HttpResponseRedirect('/role/home?returninfo=name&clicked=' + str(click_id))

        user = request.user
        teacher = Teacher.objects.get(user=user.id)

        upload_file = Courseware(name=name,
                                 file=file,
                                 teacher=teacher,
                                 )
        upload_file.save()
        upload_file.subject.add(subject)


    else:
        # return render(request, 'role:home')
        return HttpResponseRedirect('/role/home?returninfo=error')

    return HttpResponseRedirect('/role/home?returninfo=success&clicked=' + str(click_id))


def download(request):

    if 'download' in request.GET and request.GET['download']:
        d = request.GET['download']
    else:
        return HttpResponseRedirect('/')

    if 'clicked' in request.GET and request.GET['clicked']:
        c = request.GET['clicked']
    else:
        return HttpResponseRedirect('/')

    courseware = Courseware.objects.get(id=d)
    url = courseware.file.path
    if os.path.exists(url):
        format = re.findall('\.\w+$', url)

        wrapper = FileWrapper(open(url, 'rb'))
        content_type = mimetypes.guess_type(url)
        response = HttpResponse(wrapper, content_type)
        filename = courseware.name + format[0]
        response['Content-Disposition'] = "attachment; filename=%s" % filename

        return response
    else:
        return_url = '/role/home?clicked=' + str(c) + '&returninfo=download_error'
        return HttpResponseRedirect(return_url)


def Delete(request):

    if 'delete' in request.GET and request.GET['delete']:
        d = request.GET['delete']
    else:
        return HttpResponseRedirect('/')

    if 'clicked' in request.GET and request.GET['clicked']:
        c = request.GET['clicked']
    else:
        return HttpResponseRedirect('/')

    courseware = Courseware.objects.get(id=d)

    url = courseware.file.path
    if os.path.exists(url):
        os.remove(url)

    courseware.delete()

    return_url = '/role/home?clicked=' + str(c) + '&returninfo=delete'
    return HttpResponseRedirect(return_url)


class Regist(generic.View):

    template_name = 'role/regist.html'

    def get(self, request):

        if not request.user.is_superuser:
            return HttpResponseRedirect("/")

        info = ''

        if 'info' in request.GET and request.GET['info']:
            info = request.GET['info']

        context = {
            'info': info
        }

        return render(
            request,
            self.template_name,
            context,
        )


def register(request):

    print request.POST

    post_data = request.POST

    username = post_data['username']
    pw = post_data['password']
    pw_cm = post_data['pw_confirm']
    groups = post_data['groups']
    first = post_data['first']
    last = post_data['last']

    print "username is %s , pw is %s groups is %s" % (username, pw, groups)

    if username == '':
        return HttpResponse("null username")

    if pw != pw_cm:
        return HttpResponse("pass error")

    check_user = models.User.objects.filter(username=username)

    if check_user:
        return HttpResponse("username is already in sign")

    user = models.User.objects.create_user(username, "temp@temp.com", pw)
    user.is_staff = 'True'
    user.save()

    if first:
        user.first_name = first
        user.save()

    if last:
        user.last_name = last
        user.save()

    g = models.Group.objects.get(name=groups)
    user.groups.add(g)
    if "Student" == groups:
        stu = models.Student.objects
        s = models.Student(user=user)
        s.save()

    if "Teacher" == groups:
        stu = models.Teacher.objects
        s = models.Teacher(user=user)
        s.save()

    return HttpResponseRedirect('/role/regist?info=success')

# Create your views here.

templates/role/main_menu.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>menu</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script>
                var system = {
                    win: false,
                    mac: false,
{#                    xll: false,#}
{#                    ipad:false#}
                };
                //检测平台
                var p = navigator.platform;
                system.win = p.indexOf("Win") == 0;
                system.mac = p.indexOf("Mac") == 0;
{#                system.x11 = (p == "X11") || (p.indexOf("Linux") == 0);#}
{#                system.ipad = (navigator.userAgent.match(/iPad/i) != null)?true:false;#}
                //跳转语句
                if (system.win || system.mac) {
                    $(function () {
                        var H = $(window).height();
                        var wall1 = $("#wall1").height();
                        document.getElementById('wall').style.height = H + 'px';
                        document.getElementById('wall2').style.height = (H - wall1) + 'px';
                    });

                    $(window).resize(function () {
                        var H = $(window).height();
                        var wall1 = $("#wall1").height();
                        document.getElementById('wall').style.height = H + 'px';
                        document.getElementById('wall2').style.height = (H - wall1) + 'px';
                    });
                }
            </script>
</head>
<body>

<div id="wall" style="width: 100%;">

    <div class="row" style="margin: 0;" id="wall1">
        <div class="col-md-12" style="background: #252524;">
            <blockquote>
                    <h1 class="title"> Couseware <a class="title" style="font-size: medium">{{ user_type }}</a>

                    <a href="/sign_out"><button class="btn btn-link" style="font-size: 20px">Sign Out</button></a>
                </h1>
            </blockquote>
        </div>
    </div>

    <div class="row" style="margin: 0;" id="wall2">
        <div class="col-md-2" style="background: #5ec0bb; overflow-y: auto; height: 100%;" >

{#            <div class="left">#}
{#                <a href="/role/upload">#}
{#                    <button class="btn btn-danger btn-lg btn-block left_button">上传文件</button>#}
{#                </a>#}
{#            </div>#}

            {% for k,v in subject_list.items %}
                <a href="/role/home?clicked={{ k }}">
                    <button class="btn btn-danger btn-lg btn-block left_button" value={{ k }}>{{ v }}</button>
                </a>
            {% endfor %}

        </div>


        <div class="col-md-10" >

            {% if 'home' == page_type %}
                <blockquote><h1>Welcome</h1>{{ user_name }}</blockquote>
            {% endif %}


            {% if '' != returninfo %}
                <script>
                    {% if 'file' == returninfo %}
                        alert("没有选择文件");
                    {% elif 'name' == returninfo %}
                        alert("课件名为空");
                    {% elif 'download_error' == returninfo %}
                        alert("课件好像出了一些问题！");
                    {% else %}
                        alert({{ returninfo }});
                    {% endif %}
                </script>
            {% endif %}

        {% if 0 <= click_id %}
                <blockquote><a style="font-size: 20px; color: #252524; margin-right: 20px;">Subject:{{ click_name }}</a>

            {% if "Teacher" == user_type.name %}
            {#上传#}
            <span class="glyphicon glyphicon-upload" data-toggle="modal" data-target="#myModal" style="font-size: 30px; color: #337ab7;" type="upload"></span>

            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                  </div>
                    <form method="post" action="{% url 'role:upload' %}" enctype="multipart/form-data">
                  <div class="modal-body">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>课件名:</label><br>
                            <input type="text" name="name" placeholder="courseware name">
                        </div>

                        <div class="form-group">
                            <label>课件:</label>
                            <input type="file" name="upfile">
                        </div>
                        <input type="hidden" name="subject" value={{ click_id }}>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" value="submit">submit</button>
                      </div>
                    </form>
                </div>
              </div>
            </div>
{#        <a href="/role/upload"><button>123</button> </a>#}
            </blockquote>
        {% endif %}
        {% if 0 != courseware_list.size %}
            <table class="table table-striped" style="text-align: center; width: 60%; margin: auto;">
                <thead>
                    <tr>
                        <th style="padding-left: 15px;">课件名</th>
                        <th style="text-align: center;">download</th>
                        {% if 'Teacher' == user_type.name %}
                             <th style="text-align: center;">delete</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for k,v in courseware_list.items %}
                        <tr>
                            <td style="vertical-align: middle;">{{ v }}</td>
                            <td style="width: 25px;">
                                <a href="/role/download?download={{ k }}&clicked={{ click_id }}">
                                    <span class="glyphicon glyphicon-download" style="font-size: 20px; color: #337ab7;"></span>
                                </a>
                            </td>
                            {% if "Teacher" == user_type.name %}
                                <td style="width: 25px;">
                                    <a href="/role/delete?delete={{ k }}&clicked={{ click_id }}">
                                        <span class="glyphicon glyphicon-remove-circle" style="font-size: 20px; color: red;"></span>
                                    </a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <blockquote><h1>暂时没有课件</h1></blockquote>
        {% endif %}
        {% endif %}
        </div>
    </div>

</div>

</body>
</html>

templates/role/regist.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Regist</title>
    <link rel="stylesheet" href="{% static 'css/log_in.css' %}">
    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <script>

        function validate_required(filed, alerttext)
        {
            with (filed)
            {
                if (value == null || value == "")
                {
                    alert(alerttext);
                    return false;
                }
                else
                {
                    return true;
                }
            }
        }

        function validate_password(pw,repw)
        {
            if (pw.value === repw.value)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        function value_form(thisform)
        {
            with (thisform)
            {

                if (validate_password(password, pw_confirm)==false)
                {
                    password.focus();
                    alert("password error");
                    return false;
                }

                else if (validate_required(username, "username null")==false)
                {
                    username.focus();
                    return false;
                }
            }
            if(upload.username.value == ""){}
            else
            {
                upload.submit();
            }

        }

    </script>

</head>
<body>


    {% if 'success' == info %}
        <script>
            alert("注册成功！");
        </script>
    {% elif 'faild' == info %}
        <script>
            alert("注册失败！");
        </script>
    {% endif %}


    <div class="form-group",id="line" style="margin: auto; width: 320px;height: 640px; text-align: center;">
    <form name="upload" action="/role/register/" method="post" onsubmit="return value_form(this)">

        {% csrf_token %}

        <div class="login">
        <div id="line">
        <h3>注册</h3>
        </div>

        <div class="login-txt" style="height: 270px;">
            登录名:
            <br>
            <input name="username" >
            <br>
            登录密码:
            <br>
            <input name="password" type="password" >
            <br>
            再输一次:
            <br>
            <input name="pw_confirm" type="password">
            <br>
            用户姓名（可留空）：
            <br>
            <input name="first" placeholder="姓" style="width: 150px">
            <input name="last" placeholder="名" style="width: 150px">
            <br>

            <select name="groups" style="margin-top: 10px; margin-bottom: 10px">
                <option value="Teacher">Teacher</option>
                <option value="Student">Student</option>
            </select>
            <br>
    <input type="submit" class="btn btn-default btn-sm" value="Submit" id="submit" style="width: 60px">
            </div>
    <br>

        </div>

    </form>
    </div>
</body>
</html>

templates/role/student_regist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Regist</title>
</head>
<body>

Reg

<form action="/role/register/" method="post">

    {% csrf_token %}
    username:
    <br>
    <input name="username">
    <br>
    password:
    <br>
    <input name="password">
    <br>


</form>

</body>
</html>

templates/role/teacher_regist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Regist</title>

    <script>

        function validate_required(filed, alerttext)
        {
            with (filed)
            {
                if (value == null || value == "")
                {
                    alert(alerttext);
                    return false;
                }
                else
                {
                    return true;
                }
            }
        }

        function validate_password(pw,repw)
        {
            if (pw.value === repw.value)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        function value_form(thisform)
        {
            with (thisform)
            {

                if (validate_password(password, pw_confirm)==false)
                {
                    password.focus();
                    alert("password error");
                    return false;
                }

                else if (validate_required(username, "username null")==false)
                {
                    username.focus();
                    return false;
                }
            }
            if(upload.username.value == ""){}
            else
            {
                upload.submit();
            }

        }

    </script>

</head>
<body>

    Reg

<form name="upload" action="/role/register/" method="post" onsubmit="return value_form(this)">

    {% csrf_token %}
    username:
    <br>
    <input name="username" >
    <br>
    password:
    <br>
    <input name="password" type="password" >
    <br>
    repeat password:
    <br>
    <input name="pw_confirm" type="password">
    <br>

    <select name="groups">
        <option value="Teacher">Teacher</option>
        <option value="Student">Student</option>
    </select>
    <br>

    <input type="submit" value="Submit" id="submit">

</form>

</body>
</html>

templates/role/upload.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload</title>
</head>
<body>

<form method="post" action="{% url 'role:upload' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="not null">
    <input type="file" name="upfile">
    <input type="hidden" name="" value="">
    <input id="submit" value="submit" type="submit">

</form>

</body>
</html>